
# Project ID - Always keep at the top
project_id = "dupguifqyjchlmzbadav"

[api]
enabled = true
port = 54321
schemas = ["public", "storage", "graphql_public"]

[db]
port = 54322

[studio]
port = 54323

# Email testing server (Inbucket)
[inbucket]
enabled = true
port = 54324
smtp_port = 54325
pop3_port = 54326

[storage]
enabled = true
file_size_limit = "50MiB"

[auth]
enabled = true
site_url = "https://d5498fdf-9d30-4367-ace8-dffe1517b061.lovableproject.com"

[realtime]
enabled = true

# Edge Functions configuration
[functions]
enabled = true
port = 54328
[functions.acelle-stats-test]
verify_jwt = false
