
project_id = "dupguifqyjchlmzbadav"

[api]
enabled = true
port = 54321
schemas = []
extra_search_path = ["extensions"]
max_rows = 1000

[db]
port = 54322
shadow_port = 54320
major_version = 15

[studio]
enabled = true
port = 54323
api_url = "http://localhost"

[inbucket]
enabled = true
port = 54324

[storage]
enabled = true
file_size_limit = "50MiB"

[auth]
enabled = true
site_url = "http://localhost:3000"

[analytics]
enabled = false
port = 54327
vector_port = 54328

[experimental]
preserves_server_stubs = true

# Configuration des nouvelles fonctions
[functions.acelle-proxy-simple]
verify_jwt = true

[functions.test-acelle-auth]
verify_jwt = true

# Configuration des fonctions existantes
[functions.acelle-proxy]
verify_jwt = true

[functions.check-acelle-api]
verify_jwt = true

[functions.anthropic-ai]
verify_jwt = true

[functions.cors-proxy]
verify_jwt = true

[functions.delete-mission]
verify_jwt = true

[functions.delete-user]
verify_jwt = true

[functions.resend-invitation]
verify_jwt = true

[functions.sync-email-campaigns]
verify_jwt = true
